import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";

import { Roboto } from "next/font/google";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/lib/theme";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";

import Image from "next/image";

import styles from "./layout.module.scss";
import React from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        {/*<body className={`${geistSans.variable} ${geistMono.variable}`}>*/}
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <div className={styles.topbar}>
              <div className={styles.island}></div>

              <div className={styles.island}>
                <Image
                  className={styles.profile}
                  src={"/images/profile.png"}
                  width={34}
                  height={34}
                  alt={"Profile"}
                />
              </div>
            </div>
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
