// "use client";

// import React, { useEffect } from "react";

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";

import Image from "next/image";

import styles from "./layout.module.scss";

// import { Gradient } from "@/../public/scripts/Gradient.js";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // useEffect(() => {
  //   const gradient = new Gradient();
  //
  //   // @ts-expect-error I aint fixing this :nerd_emoji:
  //   gradient.initGradient("#gradient-canvas");
  // }, []);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/*<div className={styles.gradientBlur} />*/}

        {/*<canvas*/}
        {/*  id="gradient-canvas"*/}
        {/*  className={styles.gradientBackground}*/}
        {/*  data-transition-in*/}
        {/*/>*/}

        <div className={styles.topbar}>
          <div className={styles.island}></div>

          <div className={styles.island}>
            <Image
              className={styles.profile}
              src={"/images/profile.png"}
              width={34}
              height={34}
              alt={"Profile"}
            />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
